### ISSUE TITLE
Question/doc: is there any tool I could pipe to adjust references in files? 

### ISSUE THREAD

**Issue by ArnaudRinquin** [keithamus/hashmark#11]
Sorry about opening an issue for this question but in the `README` you mention that `hashmark` is meant to be piped:

> The hashmark command will output some JSON to stdout with a map of filenames and their new hashes, meaning you can pipe the hash to other programs.

The most obvious program I would like to pipe to is one that would replace references to renamed files in some other files. I searched but couldn't find one.

Does it exists? If not, I think I'll implement it.

**Comment by keithamus** [comment]
You could pipe it into a tool like [`json`](https://github.com/trentm/json) to extract the new filenames, which could then be turned into bash variables, or piped into another program - perhaps [xargs](https://en.wikipedia.org/wiki/Xargs). 

However, the point of having pipe-able output is precisely for wonderful people like you to think up cool ways to take the output data and do some awesome things with it! So please, make some awesome things and by all means let me know what you've come up with and I'll proudly add it to the readme of this project.

**Comment by ArnaudRinquin** [comment]
I started working on it already, first version should be ready by tomorrow. I'm trying to do it using node but I'm pretty sure I'll end up using `sed` or equivalent.

**Comment by keithamus** [comment]
If you need any help using node streams, let me know. You should be able to get the whole JSON map with a small amount of code, something like:

```js
var json = '';
process.stdin.setEncoding('utf8');
process.stdin.on('readable', function() {
  var chunk = process.stdin.read();
  if (chunk !== null) {
    json += chunk;
  }
});
process.stdin.on('end', function() {
  json = JSON.parse(json);
  // here you put the code to that you want, given json[originalFilename] === newFilename
});
```

**Comment by ArnaudRinquin** [comment]
So, I just published the tool, [`replaceinfiles`](https://www.npmjs.com/package/replaceinfiles) but it badly needs #12 to be merged to be fully usable (see reason in PR details).

**Comment by ArnaudRinquin** [comment]
Here is an [integration example](https://github.com/songkick/replaceinfiles/tree/master/examples/hashmark) you probably want to link to.

**Comment by keithamus** [comment]
I'm very happy to be able to close this. Thanks so much for all of your efforts @ArnaudRinquin!

![](https://media.giphy.com/media/U0nW0QagDmTwA/giphy.gif)
