### ISSUE TITLE
Does not work with directories

### ISSUE THREAD

**Issue by TheSharpieOne** [keithamus/hashmark#15]
I'm not saying that it _should_ hash directories, but it should be able to handle (add the hash _or_ ignore) directories if they happen to match the glob pattern.

Ignoring them and going strictly with using the glob pattern from the CLI (not API), adding the `nodir` option should do the trick.  But you probably want to perform this at a more core/common level to include the API.

**Comment by keithamus** [comment]
Hey @TheSharpieOne thanks for the issue! Good call on it. Fancy making a PR? What you've said sounds like a good idea to implement.

**Comment by TheSharpieOne** [comment]
Will do. I'll put something up after this holiday weekend. 

Cheers.
