### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by wayneashleyberry** [keithamus/hashmark#18]
Trying out hashmark and got an error using one of the examples from the readme.

```
hashmark ./public/**/*.{js,css} 'dist/{dir}/{name}.{hash}{ext}'
```

```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'dist/public/js/app.c005ef398a19af14e0e998e50bfb3a9a8b0e8d5fbdb98f88adbce5f25daa010c.js'
    at Error (native)

```

I'm using node `v5.4.1`.

**Comment by wayneashleyberry** [comment]
This is the actual config that I'm trying to use, which doesn't actually throw an error.. but doesn't do anything at all :(

```
hashmark 'public/**.{js,css}' 'public/build/{dir}/{name}.{hash}{ext}' --asset-map rev-manifest.json -l 8
```

**Comment by wayneashleyberry** [comment]
This is my directory structure with the desired output `build` directory.

```
.
└── public
    ├── build
    │   ├── css
    │   │   └── main.12345678.css
    │   ├── js
    │   │   └── main.12345678.js
    │   └── rev-manifest.json
    ├── css
    │   └── main.css
    └── js
        └── main.js
```

**Comment by wayneashleyberry** [comment]
Think I've narrowed it down to the `{dir}` directive.

This throws the error:

```
hashmark '**/*.{js,css}' 'build/{dir}/{name}.{hash}{ext}' -m build/rev-manifest.json -l 8
```

This works fine:

```
hashmark '**/*.{js,css}' 'build/{name}.{hash}{ext}' -m build/rev-manifest.json -l 8
```

**Comment by keithamus** [comment]
Hey @wayneashleyberry thanks for the issue.

Looks like we probably need to use `mkdirp` to ensure the destination directory exists before attempting to write to it. PRs welcome.

**Comment by wayneashleyberry** [comment]
Hi @keithamus, thanks for getting back to me

I'm made sure the directories are there now, but I'm still getting the same error.

Here are my npm scripts:

```
    "prehash": "trash public/build; mkdirp public/build/css public/build/js",
    "hash": "hashmark '**/*.{js,css}' 'build/{dir}/{name}.{hash}{ext}' -m rev-manifest.json -l 8 -c public",
```

Here's the error again:

```
❯ npm run hash

> @ prehash /Users/Wayne/github.com/rawson-properties/mandate-tool
> trash public/build; mkdirp public/build/css public/build/js


> @ hash /Users/Wayne/github.com/rawson-properties/mandate-tool
> hashmark '**/*.{js,css}' 'build/{dir}/{name}.{hash}{ext}' -m rev-manifest.json -l 8 -c public

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'build/public/css/app.e78f2653.css'
    at Error (native)

```

After running the scripts the `public/build`, `public/build/css` and `public/build/js` directories are all there but empty.

**Comment by wayneashleyberry** [comment]
That directory looks wrong...

```
build/public/css/app.e78f2653.css
```

It should be `public/build/css/...`

**Comment by wayneashleyberry** [comment]
I've also noticed that the `--cwd` flag doesn't affect the output directory

**Comment by wayneashleyberry** [comment]
This works:

```
hashmark '**/*.{js,css}' 'public/build/{name}.{hash}{ext}' -m rev-manifest.json -l 8 -c public
```

but if i use `{dir}` it breaks.

```
hashmark '**/*.{js,css}' 'public/build/{dir}/{name}.{hash}{ext}' -m rev-manifest.json -l 8 -c public
```

**Comment by keithamus** [comment]
`{dir}` is the relative directory to your script - in this case `public/css`. `--cwd` is only used for asset maps right now (see [it's usage here](https://github.com/keithamus/hashmark/blob/20b2485b06376337318ee13e5351a5dd06df9e2c/index.js#L98)). We could extend `--cwd` to also effect the template strings though, which is likely what you want.

**Comment by keithamus** [comment]
You'd need to change [this line](https://github.com/keithamus/hashmark/blob/20b2485b06376337318ee13e5351a5dd06df9e2c/index.js#L72) to, rather than pass in `stream.fileName`, pass in `path.relative(options.cwd, stream.fileName)` I believe. Although I'm not 100% sure.

**Comment by evilebottnawi** [comment]
@keithamus i have same error:
```shell
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```
Because i have directory `respond.js` and use pattern `build/**/*.*`
