### ISSUE TITLE
Output before files are finished?

### ISSUE THREAD

**Issue by krues8dr** [keithamus/hashmark#19]
I'm trying to figure out an issue I'm having combining hashmark and replaceinfiles, where I'm attempting to rename a bunch of templates, and then replace references to those templates.  As a complication, there are references to templates inside of *other* templates, since you can do partials in Angular.  I'm also building to a different directory for production than the development assets, so I pass the output of hashmark through sed for some quick string replacement.

The result, however,  _appears_ to be that replaceinfiles is complaining that the files it's trying to manipulate are missing, before hashmark is done writing the files. Ideally, replaceinfiles should be manipulating the very same files that hashmark just renamed.

Here's my command:

```
hashmark -c app/build -r -l 6 'templates/**/*.*' '{dir}/{name}-{hash}{ext}' | sed 's/:"templates\//:"build\/templates\//g' | replaceinfiles -s 'app/build/templates/**/*' -d '{dir}/{base}'
```

And the error output:
```
Error: ENOENT: no such file or directory, open 'app/build/templates/activity-item.html'
```

But if I run this as two steps, it works fine:

```
hashmark -c app/build -r -l 6 'templates/**/*.*' '{dir}/{name}-{hash}{ext}' | sed 's/:"templates\//:"build\/templates\//g' > ~/hashmark.tmp
replaceinfiles -s 'app/build/templates/**/*' -d '{dir}/{base}' < ~/hashmark.tmp
```

Adding in a few lines of debugging makes it *look* like replaceinfiles is starting before hashmark has finished.  So, is hashmark actually doing the file renaming asynchronously, or echoing its map output before it's done with the file writing?

**Comment by keithamus** [comment]
Hey @krues8dr thanks for the issue.

Hashmark does all of the work on the filesystem asynchronously, but it waits until it has completed all of its work before outputting to stdout - so that it can output one blob of JSON.

I won't have time to help you debug this issue any time soon I'm afraid. But please do feel free to ask questions, I may be able to answer them and I hope to help you where I can :smile:

**Comment by krues8dr** [comment]
Figured it out - I had something upstream that was sending output earlier and breaking everything.  Thanks for the great tool!
