### ISSUE TITLE
Question: hashmark does nothing

### ISSUE THREAD

**Issue by xtreemrage** [keithamus/hashmark#22]
I use npm tooling for my angular application, after a build, this is my dir structure.

    .
    ├── app
    ├── dist
    │   ├── app.js
    │   ├── assets
    │   │   ├── css
    │   │   │    └── file1.css
    │   │   └── images
    │   │          └── file1.css
    ...

I installed hashmark, `npm i -D hashmark`, created an npm script: `"cache": "hashmark -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'"`.

But when I run the following command, `npm run cache`, it has done nothing. I can run the script but it does not changes my files with a hash. There are no errors/warnings or something, it's just done, everything stayed the same :(.

Apparently I'm missing something, but I don't know what.  I have used this [example](https://github.com/songkick/replaceinfiles/blob/master/examples/hashmark/package.json).

version:
`npm -v = 3.10.3` 
`node -v = 6.3.1`
`hasmark = 3.1.0`

This on a windows 10 x64.

**Comment by keithamus** [comment]
@xtreemrage could you please run the following:

```bash
NODE_DEBUG=fs node ./node_modules/hashmark/index.js -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'
```

This will run the script in debug mode; if you could copy the output and paste it here we can get a better idea of what is going wrong. Thanks

**Comment by xtreemrage** [comment]
@keithamus I have tried to set it in windows, but couldn't get it to work `set NODE_DEBUG=fs` and then the command you have listed.

I only get the following
`'NODE_DEBUG' is not recognized as an internal or external command,
operable program or batch file.`

So I tried the following, `set NODE_DEBUG=fs` and then this command: `node ./node_modules/hashmark/index.js -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'`

No output, nothing -_-, do you know how to make this work?

**Comment by keithamus** [comment]
Ah sorry, missed that you were on Windows. If you open powershell you can do the following:

```powershell
$Env:NODE_DEBUG="fs"
node ./node_modules/hashmark/index.js -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'
```

If you are using the normal `cmd` command line, then I think `set` needs to be on the same line as the command, so:

```cmd
set NODE_DEBUG=fs node ./node_modules/hashmark/index.js -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'
```

Give that a try and let me know how you get on 😄

**Comment by xtreemrage** [comment]
I tried both, it runs and.... no output :(. I don't have problems with other npm packages, e.g. postcss-cli, autoprifixer on my windows 10 x64 machine.

**Comment by keithamus** [comment]
I just twigged, I've been misleading you about the command!

The _actual_ command you should run is:

```cmd
set NODE_DEBUG=fs node ./node_modules/hashmark/bin/hashmark -c dist -r -l 6 'assets/**/*.*' '{dir}/{name}-{hash}{ext}'
```
(Note the */bin/hashmark* part, rather than *index.js*)

Sorry, that was totally my fault for being an idiot.

**Comment by xtreemrage** [comment]
even when I do that, just nothing, it does not display anything when I run that command. It's just go to a new prompt `>`. I give up...

**Comment by keithamus** [comment]
What happens if you change `NODE_DEBUG=fs` to `NODE_DEBUG=cluster,net,http,fs,tls,module,timers node`?

**Comment by xtreemrage** [comment]
The same as my previous post :'(

**Comment by keithamus** [comment]
I'm really sorry @xtreemrage... I'm not really sure how I can help you now. Without any way to debug this I can't really know what's going on and so can't fix it. 

If you manage to get any further with it, do let me know and I will reopen the ticket and we can figure out whats going wrong.

**Comment by xtreemrage** [comment]
@keithamus 
No problem, thanks for the help
