### ISSUE TITLE
Upgrade cli

### ISSUE THREAD

**Issue by SimenB** [keithamus/hashmark#23]
It transitively pulls in vulnerable minimatch
https://nodesecurity.io/advisories/118

`1.0.0` of cli is released as well

**Comment by keithamus** [comment]
Thanks @SimenB. Would you like to make a PR for this?

**Comment by SimenB** [comment]
You're currently on a version more than a year and a half old, not sure what breakage has happened in the meantime... I can submit a PR for the change in `package.json` of course, but I don't know this library enough to test it properly

https://github.com/node-js-libs/cli/releases

**Comment by keithamus** [comment]
@SimenB We have a small array of tests which should hopefully be able to detect any incompatibilities (https://github.com/keithamus/hashmark/blob/master/package.json#L12-L32). If you submit a PR and our CI passes, that's enough confidence for me 😄

**Comment by SimenB** [comment]
Aight! Opened #24
