### ISSUE TITLE
replaceinfiles deprecated

### ISSUE THREAD

**Issue by robsonsobral** [keithamus/hashmark#28]
Hi, Mr. Keith.

I read your article about to use NPM as a build tool. I finally found the time to test it. Thank you for had written it. Thank you for this lib too.

Since replaceinfiles is deprecated, do you have any suggestion to replace it?

Thank you for your attention.

**Comment by keithamus** [comment]
@robsonsobral thanks for the issue. 

I dont have any suggestions for alternatives I'm afraid. I think while it says the package is deprecated (I think they mean `unmaintained` really), I would say: if it works for you now, continue to use it until it doesn't, and then fork it and add your own features. Thats kind of the wonderful thing about open source 😄.

If you do end up forking, or manage to find a suitable replacement, please let me know and I'll be happy to update the readme!
